### PR TITLE
chore(ZN-385): changes in linting and formatting rules

### PR DESCRIPTION
**Pull request by kacper-witas-tsh**
- add editorconfig
- add prettier rule to respect editorconfig rules (if prettier overrides editorconfig rule then prettier rule is taken)
- remove prettier config from eslint config because eslint is able to read .prettierrc file
- add rules/packages for linting tests
- remove unnecessary library react-test-renderer
- move testing-library packages to dev-dependencies
- bump jest packages
- apply some changes in tests according to new rules
- remove unnecessary React imports (import React from 'react')
- remove unused DoIRender component

### CODE REVIEW

**Comment by barto-tsh** [comment]
looks nice, but I've got a question according to 3rd bullet:
> remove prettier config from eslint config because eslint is able to read .prettierrc file
wouldn't it be better to have prettier config in `.eslintrc` like it was before? keeping it in single file gives us single source of truth when it comes to code style 🤔

**Comment by kacper-witas-tsh** [comment]
> 

Sound's good to me, previously we had both: prettier file and inlined config in .eslintrc

**Comment by barto-tsh** [comment]
ahh right and it was confusing 😅 so if it's possible let it be in single file 😁 of course this is not connected with editorconfig which have to be separated

**Comment by kacper-witas-tsh** [comment]
@barto-tsh actually having it inside .eslintrc has one trade-off - if you use `format document` in vscode it won't apply these rules, it will apply some prettier defaults 😞 We have ability to use linting to format because of how eslint with prettier works together but if someone uses formatting seperately (for example on save etc.) it might be not too god dev experience. I think we will have to keep it inside .prettierrc because of that. WDYT?

**Review by barto-tsh — APPROVED** [review]

**Pull request merged**
