### PR TITLE
chore(ZN-356): lint commit message and branch name

### PR DESCRIPTION
**Pull request by kacper-witas-tsh**

### CODE REVIEW

**Review by barto-tsh — DISMISSED** [review]

**Review by krzysztofkrolikowski — APPROVED** [review]
We can also avoid adding whole logic within usage of npm package
https://npm.io/package/validate-branch-name

```
{
  "husky": {
    "hooks": {
      "pre-commit": "npx validate-branch-name"
    }
  },
  "validate-branch-name": {
    "pattern": "^(feature|improvement|bugfix|hotfix|release)\/[a-zA-Z0-9\_\.\-]+$",
    "errorMsg": "bla ble"
  }
}
```

**Review by qh4r — APPROVED** [review]

**Comment by kacper-witas-tsh** [comment]
> This solution is fine, and we can also avoid adding whole logic within usage of npm package https://npm.io/package/validate-branch-name
> 
> ```
> {
>   "husky": {
>     "hooks": {
>       "pre-commit": "npx validate-branch-name"
>     }
>   },
>   "validate-branch-name": {
>     "pattern": "^(feature|improvement|bugfix|hotfix|release)\/[a-zA-Z0-9\_\.\-]+$",
>     "errorMsg": "bla ble"
>   }
> }
> ```

sounds good, I'll check that later and if it works then we can go this way

**Comment by kacper-witas-tsh** [comment]
@krzysztofkrolikowski It works great! Thanks a lot!!
image

Please reapprove ❤️

**Review by krzysztofkrolikowski — APPROVED** [review]
LGTM

**Pull request merged**
